---
title: "Supplemental Analysis"
author: "Johannes Burgers"
date: "5/27/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


left over data for doing ngram research. Not conclusive
```{r}
#Get all nested parentheses

#[()](?=[^)(]*\)[\s—-])


```

```{r sound_fury_ngrams}
sf_df <- as.data.frame(read_file("sound_and_the_fury_william_faulkner.txt"))
colnames(sf_df) <- "text" 
sf_df <- sf_df %>% 
mutate(text = gsub("[‘’]", "'", text)) %>% 
              unnest_tokens(text, text) %>%  
              summarize(text = str_c(text, collapse = " "))

# Grab all ngrams between 4 and 16 words long. These numbers were arrived at using manual fine tuning. Filter out duplicate phrases by count>1. Add the ngram length.
sf_ngram <- sf_df %>%
  unnest_ngrams(word, text, n_min = 4, n = 16) %>%
  count(word) %>%
  filter(n > 1) %>%
  mutate (ngram_length = str_count(word, "\\S+"))

#create a helper file.
# sf_short <- sf_ngram %>%
#   select(word, ngram_length) %>%
#   arrange(desc(ngram_length))



#redupe <- sf_ngram %>%
#           mutate(duplicate = str_detect(word, #sf_short$word))


sf_deduped <-
  #the map function iterates a function across the entire vector. In this case, search for each string in each string and keep track of the count.
  map_df(
    sf_ngram$word,
    ~ str_count(sf_ngram$word, .x) %>%
      sum  %>%
      set_names(.x) %>%
      enframe(name = "word", value = "count")
  ) %>%
  arrange(desc(count))

#filter out any duplicates.
sf_deduped_short <- sf_deduped %>%
  filter (count == 1)

#filter out the duplicated ngrams
sf_ngrams_filtered <- sf_ngram %>%
  inner_join(sf_deduped_short)

#recount how often each individual ngram appears in the text. There is a discrepancy between the initial ngram count and their actual appearance in the text. Not sure why, but this solves that issue. 
sf_ngrams_text_count <- sf_ngrams_filtered %>%
  mutate(text_count =  str_count(sf_df$text, word))

#Calculate text lengths.
sf_length <- sf_df %>%
  unnest_tokens(word, text) %>%
  nrow()

sf_ngrams_word_count <- sf_ngrams_text_count %>%
  mutate(total_count = ngram_length * text_count) %>%           group_by(ngram_length) %>% 
  summarise(total = sum(total_count)) %>%  
  arrange(desc(ngram_length)) %>% 
  mutate(cum_total = cumsum(total)) %>% 
  mutate(percent = total / sf_length) %>% 
    mutate(cum_percent = cum_total / sf_length)

sf_ngrams_word_count <- sf_ngrams_word_count %>% 
                                mutate(title = "sound_fury")   
```

```{r lay_dying_ngram}

ail_df <- as.data.frame(read_file("as_I_lay_dying_william_faulkner.txt"))
colnames(ail_df) <- "text" 
ail_df <- ail_df %>% 
mutate(text = gsub("[‘’]", "'", text)) %>% 
              unnest_tokens(text, text) %>%  
              summarize(text = str_c(text, collapse = " "))

# Grab all ngrams between 4 and 16 words long. These numbers were arrived at using manual fine tuning. Filter out duplicate phrases by count>1. Add the ngram length.
ail_ngram <- ail_df %>%
  unnest_ngrams(word, text, n_min = 4, n = 16) %>%
  count(word) %>%
  filter(n > 1) %>%
  mutate (ngram_length = str_count(word, "\\S+"))

#create a helper file.
# ail_short <- ail_ngram %>%
#   select(word, ngram_length) %>%
#   arrange(desc(ngram_length))



#redupe <- ail_ngram %>%
#           mutate(duplicate = str_detect(word, #ail_short$word))


ail_deduped <-
  #the map function iterates a function across the entire vector. In this case, search for each string in each string and keep track of the count.
  map_df(
    ail_ngram$word,
    ~ str_count(ail_ngram$word, .x) %>%
      sum  %>%
      set_names(.x) %>%
      enframe(name = "word", value = "count")
  ) %>%
  arrange(desc(count))

#filter out any duplicates.
ail_deduped_short <- ail_deduped %>%
  filter (count == 1)

#filter out the duplicated ngrams
ail_ngrams_filtered <- ail_ngram %>%
  inner_join(ail_deduped_short)

#recount how often each individual ngram appears in the text. There is a discrepancy between the initial ngram count and their actual appearance in the text. Not sure why, but this solves that issue. 
ail_ngrams_text_count <- ail_ngrams_filtered %>%
  mutate(text_count =  str_count(ail_df$text, word))

#Calculate text lengths.
ail_length <- ail_df %>%
  unnest_tokens(word, text) %>%
  nrow()

ail_ngrams_word_count <- ail_ngrams_text_count %>%
  mutate(total_count = ngram_length * text_count) %>%           group_by(ngram_length) %>% 
  summarise(total = sum(total_count)) %>%  
  arrange(desc(ngram_length)) %>% 
  mutate(cum_total = cumsum(total)) %>% 
  mutate(percent = total / ail_length) %>% 
  mutate(cum_percent = cum_total / ail_length)

ail_ngrams_word_count <- ail_ngrams_word_count %>% 
                                mutate(title = "as_I_lay")   

```

```{r light_in_august_ngram}
lia_df <- as.data.frame(read_file("light_in_august_william_faulkner.txt"))
colnames(lia_df) <- "text" 
lia_df <- lia_df %>% 
mutate(text = gsub("[‘’]", "'", text)) %>% 
              unnest_tokens(text, text) %>%  
              summarize(text = str_c(text, collapse = " "))

# Grab all ngrams between 4 and 16 words long. These numbers were arrived at using manual fine tuning. Filter out duplicate phrases by count>1. Add the ngram length.
lia_ngram <- lia_df %>%
  unnest_ngrams(word, text, n_min = 4, n = 16) %>%
  count(word) %>%
  filter(n > 1) %>%
  mutate (ngram_length = str_count(word, "\\S+"))

#create a helper file.
# lia_short <- lia_ngram %>%
#   select(word, ngram_length) %>%
#   arrange(desc(ngram_length))



#redupe <- lia_ngram %>%
#           mutate(duplicate = str_detect(word, #lia_short$word))


lia_deduped <-
  #the map function iterates a function across the entire vector. In this case, search for each string in each string and keep track of the count.
  map_df(
    lia_ngram$word,
    ~ str_count(lia_ngram$word, .x) %>%
      sum  %>%
      set_names(.x) %>%
      enframe(name = "word", value = "count")
  ) %>%
  arrange(desc(count))

#filter out any duplicates.
lia_deduped_short <- lia_deduped %>%
  filter (count == 1)

#filter out the duplicated ngrams
lia_ngrams_filtered <- lia_ngram %>%
  inner_join(lia_deduped_short)

#recount how often each individual ngram appears in the text. There is a discrepancy between the initial ngram count and their actual appearance in the text. Not sure why, but this solves that issue. 
lia_ngrams_text_count <- lia_ngrams_filtered %>%
  mutate(text_count =  str_count(lia_df$text, word))

#Calculate text lengths.
lia_length <- lia_df %>%
  unnest_tokens(word, text) %>%
  nrow()

lia_ngrams_word_count <- lia_ngrams_text_count %>%
  mutate(total_count = ngram_length * text_count) %>%           group_by(ngram_length) %>% 
  summarise(total = sum(total_count)) %>%  
  arrange(desc(ngram_length)) %>% 
  mutate(cum_total = cumsum(total)) %>% 
  mutate(percent = total / lia_length) %>% 
  mutate(cum_percent = cum_total / lia_length)
lia_ngrams_word_count <- lia_ngrams_word_count %>% 
                                mutate(title = "light_august")   

```

```{r}
dickens_df <- as.data.frame(read_file("great_expectations_dickens.txt"))
colnames(dickens_df) <- "text" 
dickens_df <- dickens_df %>% 
mutate(text = gsub("[‘’]", "'", text)) %>% 
              unnest_tokens(text, text) %>%  
              summarize(text = str_c(text, collapse = " "))

# Grab all ngrams between 4 and 16 words long. These numbers were arrived at using manual fine tuning. Filter out duplicate phrases by count>1. Add the ngram length.
dickens_ngram <- dickens_df %>%
  unnest_ngrams(word, text, n_min = 4, n = 16) %>%
  count(word) %>%
  filter(n > 1) %>%
  mutate (ngram_length = str_count(word, "\\S+"))

#create a helper file.
# dickens_short <- dickens_ngram %>%
#   select(word, ngram_length) %>%
#   arrange(desc(ngram_length))



#redupe <- dickens_ngram %>%
#           mutate(duplicate = str_detect(word, #dickens_short$word))


dickens_deduped <-
  #the map function iterates a function across the entire vector. In this case, search for each string in each string and keep track of the count.
  map_df(
    dickens_ngram$word,
    ~ str_count(dickens_ngram$word, .x) %>%
      sum  %>%
      set_names(.x) %>%
      enframe(name = "word", value = "count")
  ) %>%
  arrange(desc(count))

#filter out any duplicates.
dickens_deduped_short <- dickens_deduped %>%
  filter (count == 1)

#filter out the duplicated ngrams
dickens_ngrams_filtered <- dickens_ngram %>%
  inner_join(dickens_deduped_short)

#recount how often each individual ngram appears in the text. There is a discrepancy between the initial ngram count and their actual appearance in the text. Not sure why, but this solves that issue. 
dickens_ngrams_text_count <- dickens_ngrams_filtered %>%
  mutate(text_count =  str_count(dickens_df$text, word))

#Calculate text lengths.
dickens_length <- dickens_df %>%
  unnest_tokens(word, text) %>%
  nrow()

dickens_ngrams_word_count <- dickens_ngrams_text_count %>%
  mutate(total_count = ngram_length * text_count) %>%           group_by(ngram_length) %>% 
  summarise(total = sum(total_count)) %>%  
  arrange(desc(ngram_length)) %>% 
  mutate(cum_total = cumsum(total)) %>% 
  mutate(percent = total / dickens_length) %>% 
  mutate(cum_percent = cum_total / dickens_length)

dickens_ngrams_word_count <- dickens_ngrams_word_count %>% 
                                mutate(title = "expectations")   


```

```{r melville_ngram}
melville_df <- as.data.frame(read_file("moby_dick_herman_melville.txt"))
colnames(melville_df) <- "text" 
melville_df <- melville_df %>% 
mutate(text = gsub("[‘’]", "'", text)) %>% 
              unnest_tokens(text, text) %>%  
              summarize(text = str_c(text, collapse = " "))

# Grab all ngrams between 4 and 16 words long. These numbers were arrived at using manual fine tuning. Filter out duplicate phrases by count>1. Add the ngram length.
melville_ngram <- melville_df %>%
  unnest_ngrams(word, text, n_min = 4, n = 16) %>%
  count(word) %>%
  filter(n > 1) %>%
  mutate (ngram_length = str_count(word, "\\S+"))

#create a helper file.
# melville_short <- melville_ngram %>%
#   select(word, ngram_length) %>%
#   arrange(desc(ngram_length))



#redupe <- melville_ngram %>%
#           mutate(duplicate = str_detect(word, #melville_short$word))


melville_deduped <-
  #the map function iterates a function across the entire vector. In this case, search for each string in each string and keep track of the count.
  map_df(
    melville_ngram$word,
    ~ str_count(melville_ngram$word, .x) %>%
      sum  %>%
      set_names(.x) %>%
      enframe(name = "word", value = "count")
  ) %>%
  arrange(desc(count))

#filter out any duplicates.
melville_deduped_short <- melville_deduped %>%
  filter (count == 1)

#filter out the duplicated ngrams
melville_ngrams_filtered <- melville_ngram %>%
  inner_join(melville_deduped_short)

#recount how often each individual ngram appears in the text. There is a discrepancy between the initial ngram count and their actual appearance in the text. Not sure why, but this solves that issue. 
melville_ngrams_text_count <- melville_ngrams_filtered %>%
  mutate(text_count =  str_count(melville_df$text, word))

#Calculate text lengths.
melville_length <- melville_df %>%
  unnest_tokens(word, text) %>%
  nrow()

melville_ngrams_word_count <- melville_ngrams_text_count %>%
  mutate(total_count = ngram_length * text_count) %>%           group_by(ngram_length) %>% 
  summarise(total = sum(total_count)) %>%  
  arrange(desc(ngram_length)) %>% 
  mutate(cum_total = cumsum(total)) %>% 
  mutate(percent = total / melville_length) %>% 
   mutate(cum_percent = cum_total / melville_length)

melville_ngrams_word_count <- melville_ngrams_word_count %>% 
                                mutate(title = "dick")   

```

```{r}
twain_df <- as.data.frame(read_file("huckleberry_finn_mark_twain.txt"))
colnames(twain_df) <- "text" 
twain_df <- twain_df %>% 
mutate(text = gsub("[‘’]", "'", text)) %>% 
              unnest_tokens(text, text) %>%  
              summarize(text = str_c(text, collapse = " "))

# Grab all ngrams between 4 and 16 words long. These numbers were arrived at using manual fine tuning. Filter out duplicate phrases by count>1. Add the ngram length.
twain_ngram <- twain_df %>%
  unnest_ngrams(word, text, n_min = 4, n = 16) %>%
  count(word) %>%
  filter(n > 1) %>%
  mutate (ngram_length = str_count(word, "\\S+"))

#create a helper file.
# twain_short <- twain_ngram %>%
#   select(word, ngram_length) %>%
#   arrange(desc(ngram_length))



#redupe <- twain_ngram %>%
#           mutate(duplicate = str_detect(word, #twain_short$word))


twain_deduped <-
  #the map function iterates a function across the entire vector. In this case, search for each string in each string and keep track of the count.
  map_df(
    twain_ngram$word,
    ~ str_count(twain_ngram$word, .x) %>%
      sum  %>%
      set_names(.x) %>%
      enframe(name = "word", value = "count")
  ) %>%
  arrange(desc(count))

#filter out any duplicates.
twain_deduped_short <- twain_deduped %>%
  filter (count == 1)

#filter out the duplicated ngrams
twain_ngrams_filtered <- twain_ngram %>%
  inner_join(twain_deduped_short)

#recount how often each individual ngram appears in the text. There is a discrepancy between the initial ngram count and their actual appearance in the text. Not sure why, but this solves that issue. 
twain_ngrams_text_count <- twain_ngrams_filtered %>%
  mutate(text_count =  str_count(twain_df$text, word))

#Calculate text lengths.
twain_length <- twain_df %>%
  unnest_tokens(word, text) %>%
  nrow()

twain_ngrams_word_count <- twain_ngrams_text_count %>%
  mutate(total_count = ngram_length * text_count) %>%           group_by(ngram_length) %>% 
  summarise(total = sum(total_count)) %>%  
  arrange(desc(ngram_length)) %>% 
  mutate(cum_total = cumsum(total)) %>% 
  mutate(percent = total / twain_length) %>% 
  mutate(cum_percent = cum_total / twain_length)


twain_ngrams_word_count <- twain_ngrams_word_count %>% 
                          mutate(title = "huckfinn")

```

```{r}
all_totals <- twain_ngrams_word_count %>% 
              bind_rows(melville_ngrams_word_count) %>% 
              bind_rows(dickens_ngrams_word_count) %>% 
              bind_rows(lia_ngrams_word_count) %>% 
              bind_rows(ail_ngrams_word_count) %>% 
              bind_rows(sf_ngrams_word_count) %>% 
              bind_rows(ngrams_word_count) 

all_totals <- all_totals %>% 
              filter(ngram_length>6)
              

```

```{r}

word_echo_all <- plot_ly(
                all_totals,
                x = ~ngram_length,
                y = ~total,
                name =~title,
                color = ~title,
                type = 'scatter',
                mode = 'line'
)

word_echo_all




```

```{r}
library(tokenizers)

absalom_txt <- as.data.frame(read_file("absalom_cleaned_to_match_4_30_rev4.txt"))
colnames(absalom_txt) <- "text" 
absalom_sentences <- absalom_txt %>% 
  unnest_sentences(word, text) %>% 
mutate (string_length = str_count(word, "\\S+")) 
  summary(absalom_sentences$string_length)

  absalom_parenthesis <- absalom_sentences %>% 
            mutate(parentheses = gsub("[^\\(\\)]","",word)) %>% 
    filter (str_length(parentheses)>0)

summary(stri_length(stri_split_boundaries(txt, type = "sentence")[[1]]))
 
```

```{r}
absalom_read <- as.data.frame(read_file("absalom_cleaned_to_match_4_30_rev4.txt"))
colnames(absalom_read) <- "text" 
absalom_binary_tree <- absalom_read %>%
    unnest_regex(word, text,"[.?!]") %>%  
  mutate (word = str_replace_all(word, "[-—]", " ")) %>% 
mutate (string_length = str_count(word, "\\S+")) %>% 
mutate (sentence_nr = row_number()) %>% 
 mutate(parentheses = gsub("[^\\(\\)]","",word)) %>% 
  mutate(pairs = str_count(parentheses, "\\(\\)")) %>% 
  mutate(nesting = str_count(parentheses, "\\(\\("))
  
mutate(word = str_replace_all(word, " \\s*\\(","\\{"))


#this was an attempt to make a tree graph. It got too complex to think about start points and end points. 
absalom_sentences_tree <- absalom_sentences %>%
    mutate(string_length = str_length(word)) %>%
    mutate(begin = cumsum(string_length)) %>%
    mutate(open_count = str_count(word, "\\(")) %>%
    unnest_regex(middle_sentence, word, "\\(") %>%
    mutate(middle_length = str_length(middle_sentence)) %>%
    mutate(close_count = str_count(middle_sentence, "\\)")) %>%
    mutate(start_sum = cumsum(middle_length)) %>% 
    unnest_regex(close_sentence, middle_sentence, "\\)") %>% 
    mutate(close_length = str_length(close_sentence)) 
```

```{r}
#Dead code for parentheses

#get

absalom_parenthesis <- absalom_sentences %>%
  mutate(parentheses = gsub("[^\\(\\)]", "", word)) %>%
  filter (str_length(parentheses) > 0) %>%
  mutate(pairs = str_count(parentheses, "\\(\\)")) %>%
  mutate(nesting = str_count(parentheses, "\\(\\("))

absalom_parenthesis_all <- absalom_txt %>%
  mutate(parentheses = gsub("[^\\(\\)]", "", text)) %>%
  mutate(pairs = str_count(parentheses, "\\(\\)")) %>%
  mutate(nesting = str_count(parentheses, "\\(\\("))
  
absalom_internal_parentheses <- absalom_clean %>% 
                                mutate (text = gsub("[)](?=[^)(]*\\)[\\s—-])","@", text, perl = TRUE)) 

write_file(absalom_internal_parentheses$text, "internal_parenth.txt")


#This file was custom created and replaced all nested parentheses with @. There were simply too many edge cases to merit a regex expression. 

  first_clean <- as.data.frame(read_file("absalom_cleaned_to_match_4_30_rev4.txt"))
colnames(first_clean) <- "text"

first_clean_out <- first_clean %>% 
 mutate (text = gsub("[\t\n\r]","", text, perl = TRUE)) %>% 
 mutate (text = gsub( "—", " ", text, perl= TRUE))

write_file(first_clean_out$text, "first_clean.txt")

matched <- gregexpr("\\((?>[^()]|(?R))*\\)", third_clean_out$text, perl = T)
matched_again <- as.data.frame(substring(third_clean_out, matched[[1]], matched[[1]] + attr(matched[[1]], "match.length") - 1))

write_csv(matched_again, "parenthesis_trial.csv")

cleaned_parentheses <-
    as.data.frame(read_file("coded_internal_parentheses.txt"))
colnames(cleaned_parentheses) <- "text"

absalom_second_pass <- cleaned_parentheses %>% 
                                mutate (text = gsub("[)](?=[^)(]*\\)[\\s—-])","@", text, perl = TRUE)) 

write_file(absalom_second_pass$text, "second_pass.txt")


parentheses_text <- as.data.frame(str_extract_all(cleaned_parentheses$text, "\\([^()]+\\)")[[1]])
colnames(parentheses_text) <- "text"
parentheses_text_count <- nrow(parentheses_text)

nested_parentheses_text <- 
as.data.frame(str_extract_all(cleaned_parentheses$text, "@.*@")[[1]])
colnames(nested_parentheses_text) <- "text"
nested_parentheses_text_count <- nrow(nested_parentheses_text)

parentheses_text_lengths <- parentheses_text %>%
  mutate(word_count = str_count(text, "\\S+"))  

parentheses_text_longest <- max(parentheses_text_lengths$word_count)

parentheses_text_mean <- parentheses_text_lengths %>% 
 summarize(total = sum(word_count), mean = mean(word_count)) %>%
  mutate(percent = total / absalom_length)

#get

absalom_parenthesis <- absalom_sentences %>%
  mutate(parentheses = gsub("[^\\(\\)]", "", word)) %>%
  filter (str_length(parentheses) > 0) %>%
  mutate(pairs = str_count(parentheses, "\\(\\)")) %>%
  mutate(nesting = str_count(parentheses, "\\(\\("))

absalom_parenthesis_all <- absalom_txt %>%
  mutate(parentheses = gsub("[^\\(\\)]", "", text)) %>%
  mutate(pairs = str_count(parentheses, "\\(\\)")) %>%
  mutate(nesting = str_count(parentheses, "\\(\\("))
  
absalom_internal_parentheses <- absalom_clean %>% 
                                mutate (text = gsub("[)](?=[^)(]*\\)[\\s—-])","@", text, perl = TRUE)) 

write_file(absalom_internal_parentheses$text, "internal_parenth.txt")


#This file was custom created and replaced all nested parentheses with @. There were simply too many edge cases to merit a regex expression. 

  first_clean <- as.data.frame(read_file("absalom_cleaned_to_match_4_30_rev4.txt"))
colnames(first_clean) <- "text"

first_clean_out <- first_clean %>% 
 mutate (text = gsub("[\t\n\r]","", text, perl = TRUE)) %>% 
 mutate (text = gsub( "—", " ", text, perl= TRUE))

write_file(first_clean_out$text, "first_clean.txt")



```

### working code for parentheses below. Cleaned up in the final version

```{r}



```



```{r parentheticals}

#create a clean version of the text without punctuation except parentheses. #NOTE: The amount of parentheses in the text is uneven. An extra one was added at the end of chapter 6.
parentheses_file <-
    as.data.frame(read_file("faulkner_absalom_parentheses.txt"))
colnames(parentheses_file) <- "text"

parentheses_clean <- parentheses_file %>%
  mutate (text = gsub("[\t\n\r]", "", text, perl = TRUE)) %>%
  mutate (text = gsub("[—]", "", text, perl = TRUE)) %>%
  mutate(text = gsub("[‘’'\"\\“\\”\\.\\?\\!\\,]", "", text, perl = TRUE))

absalom_string <- parentheses_clean$text
```

```{python nested_sentences}

#This code snippet converts all of the nested parentheses into a list object. Full credit goes to: https://stackoverflow.com/users/68063/gareth-rees

def parenthetic_contents(string):
    """Generate parenthesized contents in string as pairs (level, contents)."""
    stack = []
    for i, c in enumerate(string):
        if c == '(':
            stack.append(i)
        elif c == ')' and stack:
            start = stack.pop()
            yield (len(stack)+1, string[start + 1: i],start, start + len(string[start + 1: i]))

py_nested_sentences = list(parenthetic_contents(r.absalom_string))
```


```{r get_python_value}
nested_sentence <- py$py_nested_sentences

names(nested_sentence[[1]]) <- c("depth", "sentence", "start", "end")

parenthetical_sentences <- do.call(rbind.data.frame, nested_sentence)
structure(parenthetical_sentences)

parenthetical_dply <- as.data.frame(matrix(unlist(nested_sentence), nrow = length(nested_sentence), byrow = TRUE))


colnames(parenthetical_dply) <- c("depth", "sentence", "start", "end")



parenthetical_dply <- parenthetical_dply %>% 
                      mutate (depth = as.numeric(depth)) %>% 
                      mutate (start = as.numeric(start)) %>% 
                      mutate (end = as.numeric (end)) %>% 
                      select(-sentence)

parenthetical_dply_one <- parenthetical_dply %>% 
                          filter(depth ==1)

parenthetical_dply_two <- parenthetical_dply %>% 
                          filter(depth ==2)

parenthetical_dply_three <- parenthetical_dply %>% 
                            filter(depth ==3)
parenthetical_dply_four <- parenthetical_dply %>% 
                            filter(depth ==4)
```

```{r zero_level_depth}

character_index <-  as.data.frame(c(1:nchar(parentheses_clean$text)) )
colnames(character_index)    <- "start"               

character_index_full <- character_index %>% 
                        mutate (end = row_number()) %>% 
                        mutate( depth = 0, .before = everything())  
                        
```

```{r all_depths}

all_depths <- character_index_full %>% 
              full_join(parenthetical_dply_one, by= "start")  %>% 
              rename(end = end.x) %>% 
              full_join(parenthetical_dply_one, by= "end")
              
blank_depths <- all_depths %>% 
                mutate(start.x = ifelse(lead(depth.y!=1),NA,start.x)) %>% 
                mutate(end = ifelse(lag(depth!=1),NA,end)) 

blank_depths$start.x[1] = 1
blank_depths$end[nrow(blank_depths)] = nrow(blank_depths)
                

main_text_breaks <- blank_depths %>%
  mutate(stops = ifelse(!is.na(start.x), start.x, end)) %>%              drop_na(stops)   %>%
    select(depth.x, stops) %>%
  rename(depth = depth.x) %>%
  rename(start = stops)

```


```{r}
full_table <- parenthetical_dply %>% 
              select(-end) %>% 
              bind_rows(main_text_breaks) %>% 
              arrange(depth)

```



```{r parenthetical_length}
parenthetical_sentences_length <- parenthetical_sentences %>% 
                                  filter(depth ==1) %>% 
                                  mutate(word_count = str_count(sentence, "\\S+")) %>% 
                                summarize(total = sum(word_count)) %>% 
                                  mutate(percent = total/absalom_length)
```


```{r parenthetical_sentence_branch}

parenthetical_long <- parenthetical_dply %>% 
                      pivot_longer(2:3,names_to = "stops")


#row.names(df1) = NA

#Number of empty rows to insert
N = 1

#Every N rows after which empty rows should be inserted
after_rows = 2



new_table <- do.call(rbind, lapply(split(parenthetical_long, ceiling(1:NROW(parenthetical_long)/after_rows)),
                      function(a) rbind(a, replace(a[1:N,], TRUE, NA))))

 parentheses_plot <- plot_ly(
                       full_table,
                       x= ~start,
                       y=~depth,
                       name  = ~depth,
                       type = 'scatter',
                       mode= 'scatter',
                       #line = list(shape = 'spline'),
                       marker= list(size = 4)
 )

 
parentheses_plot


```


```{r}
#This turned out to be a not all that relevant statistic.
black_white_pre <- dy_events_short %>%
  filter(SourceTextCode!="AA") %>%
  filter(Era %in% c("Antebellum (1831-1860)", "Pre-Removal (-1830)")) %>%
  distinct(CharacterName, .keep_all = TRUE) %>%
  count(Race) %>%
  mutate(percent = n / sum(n))
```



```{r}
#Tried to make a sunburst. Couldn't get it to work

weight_count_sunburst <- absalom_events_short %>%
  filter(PresentMentioned == "Present") %>%
  distinct(EventID, CharacterName, Race, event_words) %>%
  group_by(CharacterName) %>%
  mutate (char_word_total = sum(event_words)) %>%
  distinct(CharacterName, .keep_all = TRUE) %>%
  group_by(Race) %>%
  mutate(race_word_total = sum(char_word_total)) %>%
   mutate(race_percent = char_word_total/sum(char_word_total)) %>%
  top_n(char_word_total, n = 5) %>%
  arrange(Race, desc(char_word_total)) %>%
  mutate (parent = if_else(Race==Race[row_number(Race)+1],"", Race)) %>%
  mutate (parent = if_else(is.na(parent), Race,"")) %>%
  mutate (CharacterName = if_else(str_length(parent)>1,"",CharacterName)) %>%
  mutate (char_word_total = if_else(str_length(parent)>1,race_word_total,char_word_total))

write_csv(weight_count_sunburst, "sunburst.csv")

sunburst <- plot_ly(
            weight_count_sunburst,
             labels=~CharacterName,
    parents=~parent,
    values=~char_word_total,
    type = 'sunburst'
)

sunburst



```

